# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-23 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_year',
            field=models.CharField(max_length=4),
        ),
    ]
